package com.zycat.springbootmybatisdemo.domain;

public class UsrMmenus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.menuId
     *
     * @mbggenerated
     */
    private String menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.menuName
     *
     * @mbggenerated
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.menuType
     *
     * @mbggenerated
     */
    private String menutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.transCode
     *
     * @mbggenerated
     */
    private String transcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.isSpecial
     *
     * @mbggenerated
     */
    private String isspecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.parentMenuId
     *
     * @mbggenerated
     */
    private String parentmenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.isEnd
     *
     * @mbggenerated
     */
    private String isend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.channelId
     *
     * @mbggenerated
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_mmenus.orderIndex
     *
     * @mbggenerated
     */
    private Integer orderindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.menuId
     *
     * @return the value of usr_mmenus.menuId
     *
     * @mbggenerated
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.menuId
     *
     * @param menuid the value for usr_mmenus.menuId
     *
     * @mbggenerated
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.menuName
     *
     * @return the value of usr_mmenus.menuName
     *
     * @mbggenerated
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.menuName
     *
     * @param menuname the value for usr_mmenus.menuName
     *
     * @mbggenerated
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.menuType
     *
     * @return the value of usr_mmenus.menuType
     *
     * @mbggenerated
     */
    public String getMenutype() {
        return menutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.menuType
     *
     * @param menutype the value for usr_mmenus.menuType
     *
     * @mbggenerated
     */
    public void setMenutype(String menutype) {
        this.menutype = menutype == null ? null : menutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.transCode
     *
     * @return the value of usr_mmenus.transCode
     *
     * @mbggenerated
     */
    public String getTranscode() {
        return transcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.transCode
     *
     * @param transcode the value for usr_mmenus.transCode
     *
     * @mbggenerated
     */
    public void setTranscode(String transcode) {
        this.transcode = transcode == null ? null : transcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.isSpecial
     *
     * @return the value of usr_mmenus.isSpecial
     *
     * @mbggenerated
     */
    public String getIsspecial() {
        return isspecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.isSpecial
     *
     * @param isspecial the value for usr_mmenus.isSpecial
     *
     * @mbggenerated
     */
    public void setIsspecial(String isspecial) {
        this.isspecial = isspecial == null ? null : isspecial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.parentMenuId
     *
     * @return the value of usr_mmenus.parentMenuId
     *
     * @mbggenerated
     */
    public String getParentmenuid() {
        return parentmenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.parentMenuId
     *
     * @param parentmenuid the value for usr_mmenus.parentMenuId
     *
     * @mbggenerated
     */
    public void setParentmenuid(String parentmenuid) {
        this.parentmenuid = parentmenuid == null ? null : parentmenuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.isEnd
     *
     * @return the value of usr_mmenus.isEnd
     *
     * @mbggenerated
     */
    public String getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.isEnd
     *
     * @param isend the value for usr_mmenus.isEnd
     *
     * @mbggenerated
     */
    public void setIsend(String isend) {
        this.isend = isend == null ? null : isend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.channelId
     *
     * @return the value of usr_mmenus.channelId
     *
     * @mbggenerated
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.channelId
     *
     * @param channelid the value for usr_mmenus.channelId
     *
     * @mbggenerated
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_mmenus.orderIndex
     *
     * @return the value of usr_mmenus.orderIndex
     *
     * @mbggenerated
     */
    public Integer getOrderindex() {
        return orderindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_mmenus.orderIndex
     *
     * @param orderindex the value for usr_mmenus.orderIndex
     *
     * @mbggenerated
     */
    public void setOrderindex(Integer orderindex) {
        this.orderindex = orderindex;
    }
}